esphome:
  name: bms
  platformio_options:
    board_build.variant: esp32c3
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: dev
    platform_version: https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

web_server:
  port: 80
  include_internal: true
  ota: true

ota:
  password: !secret ota_password_bms

wifi:
  networks:
  - ssid: !secret wifi_bus_ssid
    password: !secret wifi_password
    priority: 1

  domain: bus.0l.de

  # # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "fallback-ems"
    password: !secret wifi_fallback_password
    
captive_portal:

switch:
- platform: gpio
  id: led
  name: LED
  pin:
    number: 3

external_components:
- source: github://oxan/esphome-stream-server

uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: 21
  rx_pin: 20

stream_server:
  uart_id: uart_bus
  port: 1234
