esphome:
  name: cam
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_home_ssid
  password: !secret wifi_password

  domain: .home.0l.de

  ap:
    ssid: cam-fallback
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80

logger:
api:
ota:

esp32_camera:
  name: esp32_cam
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

binary_sensor:
  - platform: status
    name: "ESP32Cam status"
    
sensor:
  - platform: wifi_signal
    name: "ESP32Cam WiFi Signal"
    update_interval: 60s
    
light:
  - platform: binary
    output: gpio_4
    name: "ESP32Cam light"

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot