substitutions:
  devicename: deerma
  upper_devicename: Humidifier
  
esphome:
  name: ${devicename}

external_components:
- source:
    type: local
    path: components

esp8266:
  board: esp_wroom_02

logger:

web_server:
  port: 80

api:
  encryption:
    key: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_home_ssid
  password: !secret wifi_password

  domain: .home.0l.de

  ap:
    ssid: "deerma-fallback"
    password: !secret wifi_password

captive_portal:

uart:
  id: uart2
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 115200

xiaomi_deerma_humidifier:
  uart_id: uart2
  id: humid

sensor:
- platform: wifi_signal
  name: "WiFi Signal Sensor"
  update_interval: 60s
  entity_category: diagnostic
